name: Database Migration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/database.yml'

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Login to Supabase
      run: supabase login
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Link to Supabase project
      run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

    - name: Run database migrations
      run: supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Generate types
      run: supabase gen types typescript --local > src/integrations/supabase/types.ts

    - name: Commit generated types
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/integrations/supabase/types.ts
        git commit -m "Update generated Supabase types" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

  validate-migration:
    name: Validate Migration Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Login to Supabase
      run: supabase login
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Link to Supabase project
      run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

    - name: Validate migration files
      run: supabase db diff --file validate_migration
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}